Repository google/oracle-toolkit, pull requests merged in 2022-08, with the labels that each got.

#117 Add metadata for July 2022 patches
  roles/common/defaults/main.yml
Labels: size/XS, lgtm, approved

#118 Add assertions and retries to gen_patch_metadata
  tools/gen_patch_metadata.py
Labels: size/XS, lgtm, approved

#119 FIX: Typo correction
  group_vars/all.yml
  roles/ora-host/tasks/main.yml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#120 Fix shell parsing for --instance-ssh-extra-args flag
  install-oracle.sh
Labels: size/XS, lgtm, approved

#121 Refactor ntpd with chronyd
  docs/user-guide.md
  roles/base-provision/defaults/main.yml
  roles/base-provision/handlers/main.yml
  roles/base-provision/tasks/main.yml
Labels: lgtm, approved, size/M

#126 fix package related issues for OEL8.5
  docs/user-guide.md
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/main.yml
  roles/rac-db-setup/tasks/rac-db-install.yml
Labels: lgtm, approved, size/M

#127 Fix incorrect ORACLE_BASE
  roles/common/defaults/main.yml
  roles/rac-gi-setup/templates/gridsetup.rsp.12.2.0.1.0.j2
  roles/rac-gi-setup/templates/gridsetup.rsp.18.0.0.0.0.j2
  roles/rac-gi-setup/templates/gridsetup.rsp.19.3.0.0.0.j2
Labels: size/XS, lgtm, approved

#123 Add asmcmd fixup for 12.2 RAC install
  roles/rac-gi-setup/tasks/rac-gi-install.yml
Labels: lgtm, approved, size/S
