Repository google/oracle-toolkit, pull requests merged in 2022-06, with the labels that each got.

#106 PR to test code coverage with prowjob. Additionally PR: fixes runtime errors, includes conditional for `cleanup-oracle`
  group_vars/all.yml
  presubmit_tests/test-pr-poc.sh
Labels: lgtm, approved, size/S

#109 Populate oracle-rel when running install-sw.yml
  install-sw.yml
Labels: size/XS, lgtm, approved

#112 Apply one off/OJVM patches separately from runInstaller
  roles/rac-db-setup/tasks/rac-db-install.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
Labels: lgtm, approved, size/M

#113 Add metadata for October 2021 patches
  docs/user-guide.md
  roles/common/defaults/main.yml
Labels: lgtm, approved, size/S
