Repository google/oracle-toolkit, pull requests merged in 2023-04, with the labels that each got.

#137 Remove jinja2 references from when clauses
  roles/rac-gi-setup/tasks/rac-asm-create.yml
Labels: size/XS, lgtm, approved

#124 Ignore errors when cleaning up mountpoints
  roles/brute-ora-cleanup/tasks/main.yml
Labels: size/XS, lgtm, approved

#146 Code to cleanup log4j remnants post install-oracle
  install-sw.yml
  roles/patch-vulns/meta/main.yml
  roles/patch-vulns/tasks/main.yml
Labels: lgtm, approved, size/M

#147 Minor fixes to the user guide documentation
  docs/user-guide.md
Labels: size/XS, lgtm, approved, needs-ok-to-test
