Repository google/oracle-toolkit, pull requests merged in 2024-01, with the labels that each got.

#158 Update prow OWNERS file
  OWNERS
Labels: size/XS, lgtm, approved

#132 Fix apply-patch.sh for RAC environments
  patch.yml
  roles/patch/tasks/rac-dbpatch.yml
  roles/patch/tasks/rac-ins-opatch.yml
  roles/patch/tasks/rac-opatch.yml
Labels: lgtm, approved, size/L

#159 Add metadata for January 2024 patches
  docs/user-guide.md
  roles/common/defaults/main.yml
Labels: lgtm, approved, size/S

#143 Don't validate opatch in a no-patch install
  roles/check-swlib/tasks/main.yml
Labels: size/XS, lgtm, approved
