Repository google/oracle-toolkit, pull requests merged in 2025-01, with the labels that each got.

#171 Fix Ansible warning about using jinja2 template variable delimiters…
  roles/base-provision/tasks/main.yml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#172 Add standard .gitattributes file and a more comprehensive .gitignore file to minimize changes of accidentally committing files that should be excluded from the repository
  .gitattributes
  .gitignore
Labels: lgtm, approved, size/M

#176 Remove formatting mistakes and inconsistencies in Markdown and sample JSON files - no changes to runnable files
  README.md
  asm_disk_config.json
  cluster_config.json
  data_mounts_config.json
  docs/code-of-conduct.md
  docs/patch-metadata.md
  docs/troubleshooting_guide.md
  docs/user-guide.md
  roles/brute-ora-cleanup/README.md
  roles/hugepages/README.md
  tools/README.md
Labels: lgtm, approved

#174 Fix for task file roles/common/tasks/populate-vars.yml & fix typo in patch name for variable gi_patches
  roles/common/defaults/main.yml
  roles/common/tasks/populate-vars.yml
Labels: lgtm, approved, size/S

#178 Add support for the latest RU patches (up to and including JAN2025).
  docs/patch-metadata.md
  docs/user-guide.md
  roles/common/defaults/main.yml
Labels: lgtm, approved, size/L

#177 Install perl to support 19c patching if installing into EL
  roles/ora-host/defaults/main.yml
Labels: size/XS, lgtm, approved

#173 Ensure that the sshd parameter ServerAliveInterval is set to avoid connection timeout issues
  install-oracle.sh
Labels: size/XS, lgtm, approved

#186 Add functionality for removing Free Edition RPM based installs
  ansible.cfg
  cleanup-oracle.sh
  roles/brute-ora-cleanup/README.md
  roles/brute-ora-cleanup/tasks/main.yml
  roles/common/handlers/main.yml
Labels: lgtm, approved, size/L

#187 Cleanup process enhancement: improved if-statement to instead check on `role_separation`
  cleanup-oracle.sh
  roles/brute-ora-cleanup/tasks/main.yml
Labels: lgtm, approved, size/S

#180 Modifying conditions for additional packages requirements on RHEL7 Marketplace, RHEL7 and OEL7
  roles/ora-host/tasks/main.yml
Labels: lgtm, approved, size/M, needs-ok-to-test

#185 Add support for Oracle 21c to the toolkit
  apply-patch.sh
  check-swlib.sh
  cleanup-oracle.sh
  docs/user-guide.md
  install-oracle.sh
  roles/common/defaults/main.yml
  roles/common/tasks/populate-swap-partition-id.yml
  roles/rac-db-setup/tasks/rac-db-install.yml
  roles/rdbms-setup/defaults/main.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
  roles/rdbms-setup/templates/db_install.rsp.sh.j2
Labels: ok-to-test, lgtm, approved, size/L, ¯\_(ツ)_/¯

#188 Rebrand "BMS Toolkit" to "Oracle Toolkit for GCP"
  OWNERS
  README.md
  cleanup-oracle.sh
  docs/_config.yml
  docs/index.html
  docs/oracle-toolkit-bm-architecture.png
  docs/oracle-toolkit-vm-architecture.png
  docs/troubleshooting_guide.md
  docs/user-guide.md
  group_vars/all.yml
  manage_devices_on_vm.sh
  presubmit_tests/test-pr-poc.sh
  roles/host-provision/tasks/ssh-keygen.yml
  roles/host-provision/tasks/user-setup.yml
  roles/host-provision/templates/hostprovision_ansible_user.j2
  roles/ora-host/tasks/main.yml
  roles/rac-db-setup/tasks/rac-db-install.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
  roles/swlib/tasks/gcscopy.yml
  tools/README.md
Labels: lgtm, approved, size/L

#183 Set the environment variable CV_ASSUME_DISTID=OEL7 before running the RDBMS and GI installers
  roles/gi-setup/tasks/gi-install.yml
  roles/rac-db-setup/tasks/rac-db-install-11.2-12.1.yml
  roles/rac-db-setup/tasks/rac-db-install.yml
  roles/rac-gi-setup/tasks/rac-gi-install.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
Labels: ok-to-test, lgtm, approved, size/L

#182 Remove allow_install_on_vm option from the install_oracle.sh script command line parameters
  check-instance.yml
  docs/user-guide.md
  install-oracle.sh
Labels: ok-to-test, lgtm, approved, size/M
