Repository google/oracle-toolkit, pull requests merged in 2025-09, with the labels that each got.

#329 Add new readiness check to ensure that specified storage parameter disk groups exist in `asm_disks`
  install-sw.yml
  prep-host.yml
  roles/common/tasks/readiness_checks.yml
Labels: lgtm, approved, size/S

#333 Override and set `ORA_DB_CONTAINER=TRUE` for Free edition installs
  install-oracle.sh
Labels: size/XS, lgtm, approved

#331 Changes to support installing Free edition on EL9 with new `os_version` key-value in `rdbms_software`
  roles/common/defaults/main.yml
  roles/rdbms-setup/tasks/main.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
  roles/rdbms-setup/tasks/rdbms-rpm-install.yml
  roles/swlib/tasks/build_file_list.yml
Labels: lgtm, approved, size/M

#337 Data Guard changes required to support deployments with XFS storage
  roles/common/defaults/main.yml
  roles/db-adjustments/defaults/main.yml
  roles/db-adjustments/templates/archivelog_mode.sh.j2
  roles/db-adjustments/templates/db_modifications.sh.j2
  roles/db-copy/tasks/active-copy.yml
  roles/dg-config/tasks/main.yml
Labels: lgtm, approved, size/M

#330 Changes to support optionally procuring software from a URL
  apply-patch.sh
  install-oracle.sh
  roles/swlib/tasks/main.yml
  roles/swlib/tasks/url_download.yml
Labels: lgtm, approved, size/L

#348 Remove DB name from data/reco directories
  roles/common/defaults/main/base_variables.yml
Labels: size/XS, lgtm, approved

#347 Address host-storage warnings for filesystem installs
  roles/host-storage/tasks/main.yml
Labels: lgtm, approved, size/S

#341 Redirect quickstart doc to new location
  docs/compute-vm-quickstart.md
  docs/user-guide.md
Labels: lgtm, approved, size/L

#354 Add logging to `apply-patch.sh` and other minor optimizations and formatting changes to shell scripts
  apply-patch.sh
  install-oracle.sh
Labels: lgtm, approved, size/L

#346 Fail early with incompatible Linux/Oracle Combinations
  compatibility-tests.yml
  install-oracle.sh
  roles/compatibility-tests/tasks/main.yml
  roles/compatibility-tests/vars/main.yml
Labels: ok-to-test, lgtm, approved, size/L

#363 Updates and optimizations to the `check-swlib` role (incl. handling URL based file names)
  check-swlib.sh
  cleanup-oracle.sh
  install-oracle.sh
  roles/check-swlib/tasks/main.yml
  roles/swlib/tasks/build_file_list.yml
Labels: lgtm, approved, size/L
