Repository google/oracle-toolkit, pull requests merged in 2025-05, with the labels that each got.

#239 Add a warning about passwords in debug logs
  docs/user-guide.md
Labels: size/XS, lgtm, approved

#238 Optimizations (fixes and enhancements) to RMAN active duplicate tasks
  roles/common/defaults/main.yml
  roles/db-copy/tasks/active-copy.yml
  roles/db-copy/templates/duplicate.cmd.j2
  roles/db-copy/templates/initaux.ora.j2
Labels: lgtm, approved, size/L

#244 Add a test case for single-instance setup on BMS
  presubmit_tests/rac-on-bms.sh
  presubmit_tests/single-instance-on-bms.sh
Labels: lgtm, approved, size/M

#241 Add task file with tasks for changing the DG protection level and redo transport mode
  config-db.yml
  roles/dg-config/defaults/main.yml
  roles/dg-config/tasks/dg_mode.yml
Labels: approved, size/L

#247 Add support for APR2025 RUs and Free Edition 23.8; Documenation fixes
  docs/user-guide.md
  roles/common/defaults/main.yml
Labels: lgtm, approved, size/M

#248 Changes to login process and search of metadata in Readme.html
  tools/gen_patch_metadata.py
Labels: lgtm, approved, size/S, needs-ok-to-test

#245 Recognize both the eDelivery and OTN file names
  docs/user-guide.md
  install-sw.yml
  roles/check-swlib/tasks/main.yml
  roles/common/defaults/main.yml
  roles/gi-setup/tasks/gi-install.yml
  roles/rac-gi-setup/tasks/rac-gi-install.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
  roles/rdbms-setup/tasks/rdbms-rpm-install.yml
  roles/swlib/tasks/gcscopy.yml
Labels: ok-to-test, lgtm, approved, size/L
