Repository google/oracle-toolkit, pull requests merged in 2025-04, with the labels that each got.

#221 Enterprise Linux 8 package installation simplification
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/main.yml
Labels: lgtm, approved, size/L

#220 Add ORAchk to the Oracle Toolkit (#35)
  check-oracle.sh
  check-oracle.yml
  docs/user-guide.md
  roles/check-oracle/files/login.sql
  roles/check-oracle/files/orachk-quicktest.sh
  roles/check-oracle/meta/main.yml
  roles/check-oracle/vars/main.yml
Labels: ok-to-test, lgtm, approved, size/XL

#228 Remove debugging comments from check-oracle.yml
  check-oracle.yml
Labels: lgtm, approved, size/S

#231 Fix usage of `oracle-toolkit` in the user guide
  docs/user-guide.md
Labels: lgtm, approved, size/M

#232 Fix repeated installation text in the user guide
  docs/user-guide.md
Labels: size/XS, lgtm, approved

#229 Run presubmit tests on a new BMS machine
  presubmit_tests/test-pr-poc.sh
Labels: lgtm, approved, size/S

#235 Switch to ssh-keygen for PEM format and clarify task names
  roles/ssh-setup/tasks/main.yml
Labels: lgtm, approved, size/M

#233 Switch from a single-instance configuration to RAC cluster
  presubmit_tests/test-pr-poc.sh
Labels: lgtm, approved, size/M

#234 Ansible cleanup, minor fixes, and spelling fix for Data Guard setup related tasks
  config-db.yml
  config-rac-db.yml
  roles/db-adjustments/defaults/main.yml
  roles/db-adjustments/meta/main.yml
  roles/db-adjustments/tasks/main.yml
  roles/db-adjustments/templates/archivelog_mode.sh.j2
  roles/db-adjustments/templates/db_modifications.sh.j2
  roles/db-copy/tasks/active-copy.yml
  roles/dg-config/tasks/main.yml
Labels: lgtm, approved, size/L

#237 Move Terraform guide to docs/
  docs/terraform.md
  terraform/README.md
Labels: lgtm, approved, size/L

#236 Improve parameter error handling for Data Guard invocations
  install-oracle.sh
Labels: lgtm, approved, size/S

#218 Add "quick start" guide on how to install Oracle on GCE end-to-end
  docs/compute-vm-quickstart.md
  docs/user-guide.md
Labels: lgtm, approved, size/L

#217 Add GCE specific user guide
  docs/compute-vm-user-guide.md
  docs/user-guide.md
Labels: lgtm, approved, size/L
