Repository google/oracle-toolkit, pull requests merged in 2025-07, with the labels that each got.

#286 Add `pipelining=true` to ansible.cfg
  ansible.cfg
Labels: size/XS, lgtm, approved

#288 Optimize tasks for playbook `check-instance.yml`
  check-instance.yml
Labels: lgtm, approved, size/M

#285 Update startup.sh and ansible_cloud_logging plugin to meet WLM requirements
  terraform/scripts/setup.sh.tpl
  tools/callback_plugins/ansible_cloud_logging.py
Labels: lgtm, approved, size/L

#289 Add --data-guard-protection-mode flag
  docs/user-guide.md
  group_vars/all.yml
  install-oracle.sh
  roles/dg-config/defaults/main.yml
  terraform/main.tf
  terraform/scripts/setup.sh.tpl
  terraform/terraform.tfvars.example
  terraform/variables.tf
Labels: lgtm, approved, size/M

#279 Add support for multi-node Data Guard deployments
  docs/terraform.md
  roles/workload-agent/tasks/create_db_user.yml
  roles/workload-agent/tasks/main.yml
  terraform/main.tf
  terraform/scripts/setup.sh.tpl
  terraform/terraform.tfvars.example
  terraform/variables.tf
  terraform/versions.tf
Labels: lgtm, approved, size/L

#287 Changes to support direct download of media on Managed Host
  docs/user-guide.md
  install-oracle.sh
  roles/swlib/tasks/gcsdirect.yml
  roles/swlib/tasks/gcstransfer.yml
  roles/swlib/tasks/main.yml
Labels: lgtm, approved, size/L

#283 Change /u01/swlib ownership to oracle:oinstall
  install-sw.yml
  roles/swlib/tasks/post-installation.yml
Labels: lgtm, approved, size/M

#284 Ansible task to query and output Oracle DBID after creation
  config-db.yml
  config-rac-db.yml
  roles/dbid-logger/meta/main.yml
  roles/dbid-logger/tasks/main.yml
Labels: lgtm, approved, size/M

#294 Add July 2025 Critical Patch Update
  docs/user-guide.md
  roles/common/defaults/main.yml
Labels: size/XS, lgtm, approved

#297 parameterize control node deletion
  terraform/main.tf
  terraform/scripts/setup.sh.tpl
  terraform/variables.tf
Labels: size/XS, lgtm, approved

#298 Remove version and provider definitions as duplicated in versions.tf
  terraform/backend.tf.example
Labels: size/XS, lgtm, approved
