Repository google/oracle-toolkit, pull requests merged in 2025-06, with the labels that each got.

#250 Update required version and add random provider
  terraform/modules/oracle_toolkit_module/versions.tf
Labels: size/XS, lgtm, approved

#251 Make assign_public_ip variable work correctly for database VM
  terraform/modules/oracle_toolkit_module/main.tf
Labels: lgtm, approved, size/S

#253 Fix HTML in user guide
  docs/user-guide.md
Labels: size/XS, lgtm, approved

#255 Replace jq with native gcloud filtering
  terraform/modules/oracle_toolkit_module/scripts/setup.sh.tpl
Labels: size/XS, lgtm, approved

#258 Add roles/logging.logWriter to service account permissions
  docs/terraform.md
Labels: size/XS, lgtm, approved

#259 Add support for --ora-release in install-oracle.sh
  docs/user-guide.md
  install-oracle.sh
  terraform/main.tf.example
  terraform/modules/oracle_toolkit_module/main.tf
  terraform/modules/oracle_toolkit_module/scripts/setup.sh.tpl
  terraform/modules/oracle_toolkit_module/variables.tf
Labels: lgtm, approved, size/M

#260 Update calculations of `kernel.shmmax` and `kernel.shmall`
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/kernel_parameters.yml
Labels: lgtm, approved, size/S

#262 Refactor Terraform and add defaults
  docs/terraform.md
  terraform/main.tf
  terraform/main.tf.example
  terraform/scripts/setup.sh.tpl
  terraform/terraform.tfvars.example
  terraform/variables.tf
  terraform/versions.tf
Labels: lgtm, approved, size/L

#263 Expose `--skip-database-config` to Terraform
  terraform/main.tf
  terraform/scripts/setup.sh.tpl
  terraform/terraform.tfvars.example
  terraform/variables.tf
Labels: lgtm, approved, size/S

#264 Make RMAN backups optional
  docs/user-guide.md
  roles/db-backups/defaults/main.yml
  roles/db-backups/tasks/main.yml
  roles/db-backups/templates/rman_delete_arch.sh.j2
  terraform/variables.tf
Labels: lgtm, approved, size/L

#267 Refactor Terraform storage
  docs/terraform.md
  terraform/main.tf
  terraform/terraform.tfvars.example
  terraform/variables.tf
Labels: lgtm, approved, size/L

#249 Retrieve DB passwords from Secret Manager
  docs/terraform.md
  docs/user-guide.md
  group_vars/all.yml
  install-oracle.sh
  roles/db-create/tasks/main.yml
  roles/ora-host/tasks/main.yml
  terraform/main.tf
  terraform/scripts/setup.sh.tpl
  terraform/terraform.tfvars.example
  terraform/variables.tf
Labels: lgtm, approved, size/M

#270 Update user-guide.md
  docs/user-guide.md
Labels: size/XS, lgtm, approved

#271 Delete public SSH key from the OS login profile
  terraform/scripts/setup.sh.tpl
Labels: size/XS, lgtm, approved

#273 Improve error handling for gcloud secret retrieval
  roles/ora-host/tasks/main.yml
  roles/ora-host/tasks/validate_passwords.yml
  terraform/terraform.tfvars.example
  terraform/variables.tf
Labels: lgtm, approved, size/L

#278 Report log output as a Terraform output
  docs/terraform.md
  terraform/main.tf
Labels: lgtm, approved, size/S

#266 Allow SGA and PGA database memory to be customized
  docs/user-guide.md
  group_vars/all.yml
  install-oracle.sh
  roles/db-create/tasks/main.yml
  roles/db-create/tasks/rac-db-create.yml
  roles/db-create/templates/dbca.rsp.sh.j2
  roles/db-create/templates/rac-dbca.rsp.11.2.0.4.0.sh.j2
  roles/db-create/templates/rac-dbca.rsp.sh.j2
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/hugepages.yml
  terraform/main.tf
  terraform/scripts/setup.sh.tpl
  terraform/variables.tf
Labels: lgtm, approved, size/L

#213 Optimize playbook "readiness" checks into a concise and consistent set of pre_tasks
  brute-cleanup.yml
  check-instance.yml
  check-swlib.yml
  config-db.yml
  config-rac-db.yml
  group_vars/all.yml
  host-provision.yml
  install-sw.yml
  patch.yml
  prep-host.yml
  roles/base-provision/defaults/main.yml
  roles/base-provision/tasks/main.yml
  roles/brute-ora-cleanup/tasks/main.yml
  roles/common/defaults/main.yml
  roles/common/tasks/readiness_checks.yml
Labels: lgtm, approved, size/L

#282 Remove swap readiness checks
  roles/common/tasks/readiness_checks.yml
Labels: size/XS, lgtm, approved

#280 Add Ansible callback plugin that pushes playbook events to Google Cloud Logging
  ansible.cfg
  docs/terraform.md
  terraform/main.tf
  terraform/scripts/setup.sh.tpl
  terraform/variables.tf
  tools/callback_plugins/ansible_cloud_logging.py
Labels: lgtm, approved, size/XL
