Repository google/oracle-toolkit, pull requests merged in 2025-08, with the labels that each got.

#300 Send a signal to Ansible_logs on startup failure and update Ansible logging plugin
  roles/ora-host/tasks/main.yml
  roles/ora-host/tasks/validate_passwords.yml
  roles/workload-agent/tasks/create_db_user.yml
  terraform/scripts/setup.sh.tpl
  tools/callback_plugins/ansible_cloud_logging.py
Labels: lgtm, approved, size/L

#304 Update UID and GID values to align with Oracle documentation
  roles/common/defaults/main.yml
Labels: lgtm, approved, size/M

#301 Replace single-instance with Data Guard test and refactor test runner script
  presubmit_tests/data-guard-on-gcp.sh
  presubmit_tests/data-guard.tfvars
Labels: lgtm, approved, size/M

#308 Renaming troubleshooting guide doc filename
  docs/troubleshooting-guide.md
Labels: size/XS, lgtm, approved

#313 Fix problem with `apply-patch.sh` not using the correct `grid_user`
  group_vars/all.yml
  patch.yml
Labels: lgtm, approved, size/M

#311 Add format=12 flag to orapwd and show errors on failure
  roles/db-copy/tasks/active-copy.yml
Labels: lgtm, approved, size/S

#316 Catch unzip errors in multiline shell commands
  roles/gi-setup/tasks/gi-install.yml
  roles/patch/tasks/rac-opatch.yml
  roles/rac-db-setup/tasks/rac-db-install-11.2-12.1.yml
  roles/rac-db-setup/tasks/rac-db-install.yml
  roles/rac-gi-setup/tasks/rac-gi-install.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
Labels: lgtm, approved, size/S

#323 Set `db_create_file_dest` when not using ASM storage
  roles/db-create/templates/dbca.rsp.sh.j2
Labels: size/XS, lgtm, approved

#325 Configure RAC single-instance presubmit tests to use Oracle Multitenant
  presubmit_tests/single-instance-on-bms.sh
Labels: size/XS, lgtm, approved

#326 Fix multitenant check when saving PDB state
  group_vars/all.yml
  roles/db-create/tasks/main.yml
  roles/db-create/tasks/rac-db-create.yml
  roles/db-create/templates/dbca.rsp.sh.j2
  roles/db-create/templates/rac-dbca.rsp.sh.j2
Labels: lgtm, approved, size/S
