Repository google/oracle-toolkit, pull requests merged in 2025-03, with the labels that each got.

#122 Disable avahi only if the package exists, and fix 12cR2 RAC installs
  roles/base-provision/defaults/main.yml
  roles/base-provision/tasks/main.yml
  roles/rac-gi-setup/tasks/rac-gi-install.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
Labels: lgtm, approved, size/M

#219 Ansible key-order fixes for `block` module tasks
  roles/brute-ora-cleanup/tasks/main.yml
  roles/db-create/tasks/rac-db-create.yml
  roles/patch/tasks/main.yml
  roles/patch/tasks/rac-opatch.yml
  roles/swlib/tasks/main.yml
Labels: lgtm, approved, size/M

#223 Fix up asmcmd in 18c in addition to 12cR2
  roles/rac-gi-setup/tasks/rac-gi-install.yml
Labels: size/XS, lgtm, approved

#224 Remove redundant check in populate-swap-partition-id
  roles/common/tasks/populate-swap-partition-id.yml
Labels: size/XS, lgtm, approved, needs-ok-to-test

#222 Adding fix for 18c Patching failing due to `rc=42 OPATCHAUTO-72043: Failed to create bundle patch object`
  roles/patch/tasks/main.yml
Labels: ok-to-test, lgtm, approved, size/S

#216 feat: Terraform module to deploy GCE instances managed by the toolkit…
  .gitignore
  data_mounts_config.json
  terraform/README.md
  terraform/backend.tf
  terraform/main.tf
  terraform/modules/oracle_toolkit_module/main.tf
  terraform/modules/oracle_toolkit_module/variables.tf
  terraform/modules/oracle_toolkit_module/versions.tf
Labels: ok-to-test, lgtm, approved, size/XL

#227 Some small terraform cleanups
  terraform/README.md
  terraform/backend.tf.example
  terraform/main.tf.example
  terraform/modules/oracle_toolkit_module/main.tf
  terraform/modules/oracle_toolkit_module/variables.tf
  terraform/modules/oracle_toolkit_module/versions.tf
Labels: lgtm, approved, size/M

#225 Add gcs fuse manual backup option
  cleanup-oracle.sh
  docs/user-guide.md
  group_vars/all.yml
  install-oracle.sh
  roles/brute-ora-cleanup/tasks/main.yml
  roles/db-backups/defaults/main.yml
  roles/db-backups/tasks/gcsfuse.yml
  roles/db-backups/tasks/gcsmanual.yml
  roles/db-backups/tasks/main.yml
Labels: ok-to-test, lgtm, approved, size/L
