Repository google/oracle-toolkit, pull requests merged in 2025-02, with the labels that each got.

#192 Align all truthy values consistently with YAML standards
  brute-cleanup.yml
  check-instance.yml
  config-db.yml
  host-provision.yml
  install-sw.yml
  patch.yml
  prep-host.yml
  roles/base-provision/tasks/main.yml
  roles/common/defaults/main.yml
  roles/db-adjustements/tasks/main.yml
  roles/db-backups/tasks/main.yml
  roles/db-backups/tasks/nfs.yml
  roles/db-copy/tasks/active-copy.yml
  roles/db-create/tasks/main.yml
  roles/db-create/tasks/rac-db-create.yml
  roles/dg-config/tasks/main.yml
  roles/gi-setup/tasks/asm-create.yml
  roles/gi-setup/tasks/gi-install.yml
  roles/gi-setup/tasks/main.yml
  roles/host-provision/tasks/config-tasks.yml
  roles/host-provision/tasks/proxy.yml
  roles/host-provision/tasks/rhel-config-tasks.yml
  roles/host-provision/tasks/user-setup.yml
  roles/hugepages/tasks/main.yml
  roles/lsnr-create/tasks/main.yml
  roles/ora-host/tasks/main.yml
  roles/patch-vulns/tasks/main.yml
  roles/patch/tasks/main.yml
  roles/patch/tasks/opatch_apply.yml
  roles/patch/tasks/rac-dbpatch.yml
  roles/patch/tasks/rac-ins-opatch.yml
  roles/patch/tasks/rac-opatch.yml
  roles/patch/tasks/sql_patch.yml
  roles/pwgen/tasks/main.yml
  roles/rac-db-setup/tasks/rac-db-install-11.2-12.1.yml
  roles/rac-db-setup/tasks/rac-db-install.yml
  roles/rac-gi-setup/tasks/rac-asm-create.yml
  roles/rac-gi-setup/tasks/rac-gi-install.yml
  roles/rac-lsnr-firewall/tasks/main.yml
  roles/rdbms-setup/tasks/main.yml
  roles/rdbms-setup/tasks/rdbms-install.yml
  roles/ssh-setup/tasks/main.yml
  roles/swlib/tasks/gcloud.yml
  roles/swlib/tasks/gcsfuse.yml
  roles/swlib/tasks/main.yml
  roles/swlib/tasks/nfs.yml
  roles/validation-scripts/tasks/main.yml
Labels: lgtm, approved, size/XL

#191 Simplify jmespath check
  check-instance.yml
Labels: lgtm, approved, size/S

#194 Remove duplicate `hugepages` role call from the the `meta/main.yml` file
  roles/ora-host/meta/main.yml
Labels: size/XS, lgtm, approved

#189 Testing `--tags` & `--skip-tags` options to selectively run and skip tasks. Updating `user-guide.md` with relevant instructions on how to use `--tags` and `--skip-tags` options.
  docs/user-guide.md
  roles/ssh-setup/tasks/main.yml
Labels: lgtm, approved, size/M, needs-ok-to-test

#101 Initial cut of host provisioning documentation
  docs/host-provision-logical-fork-points.png
  docs/host-provisioning.md
  docs/user-guide.md
Labels: lgtm, approved, size/M

#195 Update and optimize the "Install Oracle required packages" tasks and related lists
  roles/base-provision/tasks/main.yml
  roles/brute-ora-cleanup/tasks/main.yml
  roles/common/defaults/main.yml
  roles/db-backups/tasks/nfs.yml
  roles/gi-setup/tasks/gi-install.yml
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/main.yml
  roles/rdbms-setup/tasks/rdbms-rpm-install.yml
  roles/swlib/tasks/gcloud.yml
  roles/swlib/tasks/gcsfuse.yml
  roles/swlib/tasks/nfs.yml
Labels: lgtm, approved, size/L

#196 Ansible linting and formatting adjustments (no logic changes)
  check-instance.yml
  roles/base-provision/handlers/main.yml
  roles/check-swlib/tasks/main.yml
  roles/db-create/tasks/rac-db-create.yml
  roles/dg-config/tasks/main.yml
  roles/gi-setup/tasks/gi-install.yml
  roles/hugepages/tasks/main.yml
  roles/ora-host/tasks/main.yml
  roles/patch/tasks/opatch_apply.yml
  roles/patch/tasks/rac-dbpatch.yml
  roles/patch/tasks/rac-opatch.yml
Labels: lgtm, approved, size/M

#198 Add support for installing the latest Oracle Database 23ai Free Edition: version `23.7.0.25.01`
  docs/user-guide.md
  roles/brute-ora-cleanup/README.md
  roles/common/defaults/main.yml
  roles/db-create/defaults/main.yml
  roles/rdbms-setup/defaults/main.yml
Labels: lgtm, approved, size/M

#200 Remove duplicate definition of the `rdbms_software` variable
  roles/rdbms-setup/defaults/main.yml
Labels: lgtm, approved, size/L

#199 Optimize kernel parameter settings and remove duplicate section from the `hugepages` role
  roles/hugepages/README.md
  roles/hugepages/tasks/main.yml
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/kernel_parameters.yml
  roles/ora-host/tasks/main.yml
Labels: lgtm, approved, size/L

#201 Add options to pass configurations from JSON files directly in CLI
  cleanup-oracle.sh
  docs/user-guide.md
  install-oracle.sh
Labels: lgtm, approved, size/L, needs-ok-to-test

#202 Fix issue with snapshot controlfile location; Formatting adjustments and RMAN script standardization
  roles/db-backups/templates/rman_arch_backup.sh.j2
  roles/db-backups/templates/rman_full_backup.sh.j2
Labels: lgtm, approved, size/M

#203 Remove orhpaned template files
  roles/base-provision/templates/dnsmasq.conf.j2
  roles/base-provision/templates/resolv.conf.j2
Labels: lgtm, approved, size/S

#205 Set CV_ASSUME_DISTID for RAC DBCA runs
  roles/db-create/tasks/rac-db-create.yml
Labels: lgtm, approved, size/S

#204 Rename `data_diskgroup` and `reco_diskgroup` to `data_destination` and `reco_destination` for accuracy and versatility
  README.md
  docs/troubleshooting_guide.md
  docs/user-guide.md
  group_vars/all.yml
  install-oracle.sh
  presubmit_tests/test-pr-poc.sh
  roles/common/defaults/main.yml
  roles/db-backups/templates/rman_arch_backup.sh.j2
  roles/db-backups/templates/rman_full_backup.sh.j2
  roles/db-create/templates/dbca.rsp.sh.j2
  roles/db-create/templates/rac-dbca.rsp.11.2.0.4.0.sh.j2
  roles/db-create/templates/rac-dbca.rsp.sh.j2
Labels: lgtm, size/L

#208 Force pkcs1 key generation to make Oracle CVU happy
  roles/ssh-setup/tasks/main.yml
Labels: size/XS, lgtm, approved

#209 Add `1MB` to Ansible fact `ansible_memtotal_mb` to account for rounding (down) errors
  roles/hugepages/tasks/main.yml
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/kernel_parameters.yml
Labels: lgtm, approved, size/S

#207 Fix RAC status check on archivelog_mode.sh.j2
  roles/db-adjustements/templates/archivelog_mode.sh.j2
Labels: size/XS, lgtm, approved

#206 Move and optimize Linux hugepages tasks
  prep-host.yml
  roles/brute-ora-cleanup/tasks/main.yml
  roles/hugepages/defaults/main.yml
  roles/ora-host/defaults/main.yml
  roles/ora-host/tasks/hugepages.yml
  roles/ora-host/tasks/main.yml
Labels: lgtm, approved, size/L

#210 Remove 19c base zip files from log4j list
  roles/patch-vulns/tasks/main.yml
Labels: size/XS, lgtm, approved

#211 Permit periods, dashes, underscores in SSH usernames
  install-oracle.sh
Labels: size/XS, lgtm, approved

#212 Refactor ohasd shutdown in cleanup playbook
  roles/brute-ora-cleanup/tasks/main.yml
Labels: size/XS, lgtm, approved

#214 Fix prow owner GitHub username
  OWNERS
Labels: size/XS, lgtm, approved
